---

- id: check-rst
  name: Check RST
  description: This hook checks json files for parseable syntax.
  entry: check-rst
  language: python
  types: [rst]
  # for backward compatibility
  files: ''
  minimum_pre_commit_version: 0.15.0

- id: check-git-commit-message
  name: Check Git commit message
  description: This hook checks Git commit message to ensure is valid
  entry: check-git-commit-message
  language: python
  types: []
  # for backward compatibility
  files: ''
  minimum_pre_commit_version: 0.15.0
  stages:
    - commit-msg
