---

language: 'python'
sudo: False

env:
  matrix:
    - TOXENV='py34'
    - TOXENV='py35'
    - TOXENV='py36'
install:
  - 'pip install coveralls tox-travis'
script:
  - 'tox -e "${TOXENV}"'
after_success:
  - 'coveralls'
